question = {"1": "Anxiété",
            "2": "Sociabilité",
            "3": "Imagination",
            "4": "Confiance en l’autre",
            "5": "Combativité - Recherche de résultats",
            "6": "Colère et hostilité",
            "7": "Sociabilité",
            "8": "Intérêts artistiques",
            "9": "Indolence ",
            "10": "Autodiscipline",
            "11": "Morosité/contentement",
            "12": "Sens des compétences",
            "13": "Profondeur des émotions",
            "14": "Altruisme",
            "15": "",
            "16": "Sociabilité",
            "17": "",
            "18": "Recherche de stimulation",
            "18": "Volonté d’expérimenter",
            "19": "Colère et hostilité ",
            "20": "Combativité",
            "21": "Recherche de stimulation",
            "22": "",
            "23": "Curiosité intellectuelle ",
            "24": "Modestie",
            "25": "Circonspection",
            "26": "Sensibilité au stress",
            "27": "",
            "28": "Conformité",
            "29": "Affectation ",
            "31": "Anxiété",
            "32": "Sociabilité",
            "33": "",
            "34": "Confiance en l’autre",
            "35": "Sens des responsabilités",
            "36": "Colère et hostilité",
            "37": "Aménité",
            "38": "Profondeur des émotions",
            "39": "Indolence ",
            "40": "Ordre",
            "41": "Morosité/contentement",
            "41" : "-Émotions positives"
            "42": "Combativité - Recherche de résultats",
            "43": "Sympathie",
            "44": "Sympathie",
            "45": "Sincérité",
            "46": "Anxiété",
            "47": "-Sociabilité",
            "47": "Volonté d’expérimenter ",
            "48": "-Recherche de stimulation",
            "49": "Colère et hostilité",
            "50": "Conformité",
            "51": "-Recherche de stimulation",
            "52": "Recherche de stimulation",
            "53": "-Curiosité intellectuelle ",
            "54": "Modestie",
            "55": "Combativité - Recherche de résultats",
            "56": "-Circonspection",
            "57": "Recherche de stimulation",
            "57": "Émotions positives",
            "58": "Profondeur des émotions",
            "59": "Sympathie",
            "60": "-Circonspection",
            "61": "Anxiété",
            "62": "Sociabilité",
            "63": "",
            "64": "Conformité",
            "65": "Sens des responsabilités",
            "66": "Colère et hostilité ",
            "67": "-Sociabilité",
            "68": "-Intérêts artistiques",
            "69": "Indolence ",
            "70": "Ordre",
            "71": "Morosité/contentement",
            "71": "Émotions positives",
            "72": "Circonspection",
            "73": "",
            "74": "-Affectation ",
            "75": "",
            "76": "Sociabilité",
            "77": "Volonté d’expérimenter ",
            "78": "-Niveau d’activité",
            "79": "Colère et hostilité",
            "80": "-Combativité - Recherche de résultats",
            "81": "Autodiscipline",
            "82": "",
            "83": "-Curiosité intellectuelle",
            "84": "Modestie",
            "85": "",
            "86": "-Sens des compétences",
            "87": "Émotions positives",
            "88": "Conformité",
            "89": "-Sympathie",
            "90": "",
            "91": "Sensibilité au stress",
            "92": "-Sociabilité",
            "93": "Curiosité intellectuelle ",
            "94": "Confiance en l’autre",
            "95": "Sens des compétences",
            "96": "Affectation ",
            "97": "Sociabilité",
            "98": "Intérêts artistiques",
            "99": "-Tolérance à la diversité",
            "100": "Ordre",
            "101": "Émotions positives",
            "102": "-Volonté d’expérimenter",
            "102": "-Combativité - Recherche de résultats",
            "103": "-Sympathie",
            "104": "-Sympathie",
            "104": "-Altruisme",
            "105": "-Sens des responsabilités",
            "106": "Affectation ",
            "107": "-Anxiété",
            "108": "Conformité",
            "109": "Colère et hostilité",
            "109": "Sympathie",
            "110": "Sens des responsabilités",
            "111": "Autodiscipline",
            "112": "",
            "113": "-Curiosité intellectuelle ",
            "114": "Modestie",
            "115": "Autodiscipline",
            "116": "Sensibilité au stress",
            "117": "Émotions positives",
            "118": "",
            "119": "Sympathie",
            "120": "-Circonspection",
        }
