QUESTION = {"1": "Anxiete",
            "2": "Sociabilite",
            "3": "Imagination",
            "4": "Confiance_n_autre",
            "5": "Combativite_Recherche_de_resultats",
            "6": "Colere_et_hostilite",
            "7": "Sociabilite",
            "8": "Interets_artistiques",
            "9": "Indolence ",
            "10": "Autodiscipline",
            "11": "Morosite_contentement",
            "12": "Sens_des_competences",
            "13": "Profondeur_des_emotions",
            "14": "Altruisme",
            "15": "",
            "16": "Sociabilite",
            "17": "",
            "18": "Recherche_de_stimulation",
            "18": "Volonte_experimenter",
            "19": "Colere_et_hostilite ",
            "20": "Combativite",
            "21": "Recherche_de_stimulation",
            "22": "",
            "23": "Curiosite_intellectuelle ",
            "24": "Modestie",
            "25": "Circonspection",
            "26": "Sensibilite_au_stress",
            "27": "",
            "28": "Conformite",
            "29": "Affectation ",
            "31": "Anxiete",
            "32": "Sociabilite",
            "33": "",
            "34": "Confiance_en_autre",
            "35": "Sens_des_responsabilites",
            "36": "Colere_et_hostilite",
            "37": "Amenite",
            "38": "Profondeur_des_emotions",
            "39": "Indolence",
            "40": "Ordre",
            "41": "Morosite_contentement",
            "41" : "-emotions_positives"
            "42": "Combativite_Recherche_de_resultats",
            "43": "Sympathie",
            "44": "Sympathie",
            "45": "Sincerite",
            "46": "Anxiete",
            "47": "-Sociabilite",
            "47": "Volonte_experimenter ",
            "48": "-Recherche_de_stimulation",
            "49": "Colere_et_hostilite",
            "50": "Conformite",
            "51": "-Recherche_de_stimulation",
            "52": "Recherche_de_stimulation",
            "53": "-Curiosite_intellectuelle ",
            "54": "Modestie",
            "55": "Combativite_Recherche_de_resultats",
            "56": "-Circonspection",
            "57": "Recherche_de_stimulation",
            "57": "emotions_positives",
            "58": "Profondeur_des_emotions",
            "59": "Sympathie",
            "60": "-Circonspection",
            "61": "Anxiete",
            "62": "Sociabilite",
            "63": "",
            "64": "Conformite",
            "65": "Sens_des_responsabilites",
            "66": "Colere_et_hostilite ",
            "67": "-Sociabilite",
            "68": "-Interets_artistiques",
            "69": "Indolence ",
            "70": "Ordre",
            "71": "Morosite_contentement",
            "71": "emotions positives",
            "72": "Circonspection",
            "73": "",
            "74": "-Affectation ",
            "75": "",
            "76": "Sociabilite",
            "77": "Volonte_experimenter ",
            "78": "-Niveau_activite",
            "79": "Colere_et_hostilite",
            "80": "-Combativite_Recherche_de_resultats",
            "81": "Autodiscipline",
            "82": "",
            "83": "-Curiosite intellectuelle",
            "84": "Modestie",
            "85": "",
            "86": "-Sens des competences",
            "87": "emotions positives",
            "88": "Conformite",
            "89": "-Sympathie",
            "90": "",
            "91": "Sensibilite_au_stress",
            "92": "-Sociabilite",
            "93": "Curiosite_intellectuelle ",
            "94": "Confiance_en_autre",
            "95": "Sens_des_competences",
            "96": "Affectation ",
            "97": "Sociabilite",
            "98": "Interets_artistiques",
            "99": "-Tolerance_a_la_diversite",
            "100": "Ordre",
            "101": "emotions_positives",
            "102": "-Volonte_experimenter",
            "102": "-Combativite_Recherche_de_resultats",
            "103": "-Sympathie",
            "104": "-Sympathie",
            "104": "-Altruisme",
            "105": "-Sens_des_responsabilites",
            "106": "Affectation ",
            "107": "-Anxiete",
            "108": "Conformite",
            "109": "Colere_et_hostilite",
            "109": "Sympathie",
            "110": "Sens_des_responsabilites",
            "111": "Autodiscipline",
            "112": "",
            "113": "-Curiosite_intellectuelle ",
            "114": "Modestie",
            "115": "Autodiscipline",
            "116": "Sensibilite_au_stress",
            "117": "emotions_positives",
            "118": "",
            "119": "Sympathie",
            "120": "-Circonspection",
        }

























